### ISSUE TITLE
nml - getmlst Tool on Galaxy

### ISSUE THREAD

**Issue by JayanthiGangiredla** [apetkau/snvphyl-galaxy#1] opened 2022-05-26 02:45 UTC
Hi all,

We would like to request you to update getmlst tool on galaxy repo https://toolshed.g2.bx.psu.edu/repository?repository_id=5634a03143d6f21d.

Problem is the tool outputs the profile sequences but it doesn't give an output on MLST definitions for any species. Fixing the tool would be very useful for workflow development of MLST analysis.

Thanks,
Jayanthi Gangiredla

**Comment by apetkau** [comment] 2022-05-26 14:11
Thank you for reporting this. This is a duplicate of this issue https://github.com/phac-nml/galaxy_tools/issues/221 and so the version posted here will be closed.

**Closed as completed by apetkau** 2022-05-26 14:11 UTC
Labels: duplicate
